### ISSUE TITLE
Decimal Value in the EDGE_WEIGHT_SECTION

### ISSUE THREAD

**Issue by IssaIssa1** [stephenlsmith/GLNS.jl#2]
I am trying to build my dataset based based on the dataset structure and documentation you provided. I have decimal values in a cost between two nodes. When I try to run it it return an error. I tried to use on integers it works. Would you mind advise on the matter

**Comment by stephenlsmith** [comment]
The solver only accepts integer edge weights (this is typical of TSP solvers).  If you have decimal values, the best way to handle them is to multiply by a large constant (say 10,000) and then round to the nearest integer.
