### ISSUE TITLE
Start from a specified state

### ISSUE THREAD

**Issue by IssaIssa1** [stephenlsmith/GLNS.jl#3]
Hi, 

have you investigated the possibility of forcing the tour to start in one start and or end in specific one?
Like starting in state 1 and ending in state 2 or back to 1

**Comment by stephenlsmith** [comment]
We don't have a special setting for this, but you can find the solution by inputing a distance matrix with the following modifications:

1) Add one extra dummy node d to your instance
2) connect the dummy node to your start node s and end node g with edge lengths of zero.
3) connect the dummy node to all other nodes in your instance with a large edge cost (for example, a multiple of the longest edge length in your instance)

The resulting solution will visit the goal, dummy node, and start in sequence.  That is, the solution will have the form: s --> (all other nodes in some order) --> g --> d --> s.  You can then just delete the edges {g,d} and {d,s} from the output to obtain your solution.

**Comment by IssaIssa1** [comment]
Thank you for your help!

**Comment by IssaIssa1** [comment]
I figured out the GLNS solution is cycle form. So it will finish in the same state it started with. I have implemented a solution for specifying a starting state s in a graph search algorithm using a dummy node with a cost of zero to s and large edge cost for the rest, but it returns the cost of going back to the dummy state which needs to be removed. Is there a more efficient way of achieving this?

**Comment by stephenlsmith** [comment]
Yes, the solver does find the shortest cycle (tour) that visits one vertex
in each set.  If you have a designated start vertex, then in your problem
instance you should create a set with just the start vertex in it.  This
vertex will then appear in the resulting tour.  You can then just rotate
the list of vertices in the tour so the start vertex appears first.
