### ISSUE TITLE
Understanding Code: Optimizing Current Tour after Accepting the Trial  

### ISSUE THREAD

**Issue by IssaIssa1** [stephenlsmith/GLNS.jl#4]
In GLNS.jl from lines 78 - 82. Why would you optimize the current tour   opt_cycle!(current, dist, sets, membership, param, setdist, "full") when in any case if you accepted the trial current will be trial (current = trial)? 

here's the python logic on how I read you code.
```if accepttrial_noparam(trial.cost, current.cost, param['prob_accept']) or accepttrial(trial.cost, current.cost, temperature):
    if param['mode'] == "slow":
        opt_cycle(current, dist, sets, membership, param, setdist, "full")
    current = trial```

**Comment by stephenlsmith** [comment]
Thanks for noticing.  I believe you're right that this line unnecessary as it is overwritten on the next line.  It looks like the it should call opt_cycle on trial rather than current.  I'll look into this, but since it's just potentially an unnecessary operation, I'll close this comment.
